name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install prerequisites
      run: sudo apt-get install -y perl libperl-critic-perl perltidy
    - name: perl check
      run: perl -c btrfs-list
    - name: perlcritic
      run: perlcritic btrfs-list
    - name: perltidy
      run: |
        perltidy --paren-tightness=2 --square-bracket-tightness=2 --brace-tightness=2 --maximum-line-length=180 btrfs-list
        if cmp btrfs-list btrfs-list.tdy; then
          echo "OK: perltidy didn't find any change to make"
        else
          echo "KO: perltidy found changes to make:"
          diff -u btrfs-list btrfs-list.tdy
          exit 1
        fi
